/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.DaoProductos;
import java.awt.BorderLayout;
import java.util.List;
import javax.swing.JOptionPane;
import modelo.productos;
import notification.Notification;

/**
 *
 * @author sergi
 */
public class MenuPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        Home h = new Home();
        h.setSize(1200,1200);
        h.setLocation(0, 0);
        CONTENEDOR.removeAll();
        CONTENEDOR.add(h,BorderLayout.CENTER);
        CONTENEDOR.revalidate();
        CONTENEDOR.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnHome = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnClientes = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnCategorias = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnProveedores = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnSalir = new RSMaterialComponent.RSButtonMaterialIconDos();
        jSeparator1 = new javax.swing.JSeparator();
        btnUsuarios = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnAcercaDe = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnProductos = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnGraficos = new RSMaterialComponent.RSButtonMaterialIconDos();
        btnReporteFactura = new RSMaterialComponent.RSButtonMaterialIconDos();
        CONTENEDOR = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        jLabel1.setText("     INVENTARIO");

        btnHome.setBackground(new java.awt.Color(204, 204, 255));
        btnHome.setForeground(new java.awt.Color(0, 0, 0));
        btnHome.setText("HOME");
        btnHome.setBackgroundHover(new java.awt.Color(204, 204, 255));
        btnHome.setForegroundIcon(new java.awt.Color(51, 51, 51));
        btnHome.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnHome.setForegroundText(new java.awt.Color(0, 0, 0));
        btnHome.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HOME);
        btnHome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHomeActionPerformed(evt);
            }
        });

        btnClientes.setBackground(new java.awt.Color(204, 204, 255));
        btnClientes.setText("CLIENTES");
        btnClientes.setBackgroundHover(new java.awt.Color(204, 204, 255));
        btnClientes.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnClientes.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnClientes.setForegroundText(new java.awt.Color(0, 0, 0));
        btnClientes.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PEOPLE);
        btnClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClientesActionPerformed(evt);
            }
        });

        btnCategorias.setBackground(new java.awt.Color(204, 204, 255));
        btnCategorias.setText("CATEGORIAS");
        btnCategorias.setBackgroundHover(new java.awt.Color(204, 204, 255));
        btnCategorias.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnCategorias.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnCategorias.setForegroundText(new java.awt.Color(0, 0, 0));
        btnCategorias.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.DASHBOARD);
        btnCategorias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCategoriasActionPerformed(evt);
            }
        });

        btnProveedores.setBackground(new java.awt.Color(204, 204, 255));
        btnProveedores.setText("PROVEEDORES");
        btnProveedores.setBackgroundHover(new java.awt.Color(204, 204, 255));
        btnProveedores.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnProveedores.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnProveedores.setForegroundText(new java.awt.Color(0, 0, 0));
        btnProveedores.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.FLARE);
        btnProveedores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProveedoresActionPerformed(evt);
            }
        });

        btnSalir.setBackground(new java.awt.Color(204, 204, 255));
        btnSalir.setText("SALIR");
        btnSalir.setActionCommand("");
        btnSalir.setBackgroundHover(new java.awt.Color(204, 204, 255));
        btnSalir.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnSalir.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnSalir.setForegroundText(new java.awt.Color(0, 0, 0));
        btnSalir.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.EXIT_TO_APP);
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        btnUsuarios.setBackground(new java.awt.Color(204, 204, 255));
        btnUsuarios.setText("USUARIOS");
        btnUsuarios.setBackgroundHover(new java.awt.Color(204, 204, 255));
        btnUsuarios.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnUsuarios.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnUsuarios.setForegroundText(new java.awt.Color(0, 0, 0));
        btnUsuarios.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.GROUP_ADD);
        btnUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUsuariosActionPerformed(evt);
            }
        });

        btnAcercaDe.setBackground(new java.awt.Color(204, 204, 255));
        btnAcercaDe.setText("ACERCA DE");
        btnAcercaDe.setActionCommand("");
        btnAcercaDe.setBackgroundHover(new java.awt.Color(204, 204, 255));
        btnAcercaDe.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnAcercaDe.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnAcercaDe.setForegroundText(new java.awt.Color(0, 0, 0));
        btnAcercaDe.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.HELP);
        btnAcercaDe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAcercaDeActionPerformed(evt);
            }
        });

        btnProductos.setBackground(new java.awt.Color(204, 204, 255));
        btnProductos.setText("PRODUCTOS");
        btnProductos.setBackgroundHover(new java.awt.Color(204, 204, 255));
        btnProductos.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnProductos.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnProductos.setForegroundText(new java.awt.Color(0, 0, 0));
        btnProductos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.RECEIPT);
        btnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProductosActionPerformed(evt);
            }
        });

        btnGraficos.setBackground(new java.awt.Color(204, 204, 255));
        btnGraficos.setText("GRÁFICOS");
        btnGraficos.setBackgroundHover(new java.awt.Color(204, 204, 255));
        btnGraficos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnGraficos.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnGraficos.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnGraficos.setForegroundText(new java.awt.Color(0, 0, 0));
        btnGraficos.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.GRAPHIC_EQ);
        btnGraficos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraficosActionPerformed(evt);
            }
        });

        btnReporteFactura.setBackground(new java.awt.Color(204, 204, 255));
        btnReporteFactura.setText("REPORTE/FACTURA");
        btnReporteFactura.setActionCommand("Reporte y Facturas");
        btnReporteFactura.setBackgroundHover(new java.awt.Color(204, 204, 255));
        btnReporteFactura.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReporteFactura.setEffectFocus(true);
        btnReporteFactura.setForegroundIcon(new java.awt.Color(0, 0, 0));
        btnReporteFactura.setForegroundIconHover(new java.awt.Color(0, 0, 0));
        btnReporteFactura.setForegroundText(new java.awt.Color(0, 0, 0));
        btnReporteFactura.setIcons(rojeru_san.efectos.ValoresEnum.ICONS.PAGES);
        btnReporteFactura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteFacturaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addComponent(jSeparator1)
                .addContainerGap())
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnReporteFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCategorias, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProveedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addComponent(btnGraficos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnReporteFactura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAcercaDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        CONTENEDOR.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout CONTENEDORLayout = new javax.swing.GroupLayout(CONTENEDOR);
        CONTENEDOR.setLayout(CONTENEDORLayout);
        CONTENEDORLayout.setHorizontalGroup(
            CONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1057, Short.MAX_VALUE)
        );
        CONTENEDORLayout.setVerticalGroup(
            CONTENEDORLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(CONTENEDOR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CONTENEDOR, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(28, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHomeActionPerformed
      btnHome.setSelected(true);
      btnCategorias.setSelected(false);
      btnClientes.setSelected(false);
      btnProveedores.setSelected(false);
      btnUsuarios.setSelected(false);
      btnAcercaDe.setSelected(false);
      btnGraficos.setSelected(false);
          btnReporteFactura.setSelected(false);
        Home h = new Home();
    h.setSize(953, 768);
    h.setLocation(0, 0);
    CONTENEDOR.removeAll();
    CONTENEDOR.add(h, BorderLayout.CENTER);
    CONTENEDOR.revalidate();
    CONTENEDOR.repaint();
    }//GEN-LAST:event_btnHomeActionPerformed

    private void btnClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClientesActionPerformed
      btnHome.setSelected(false);
      btnCategorias.setSelected(false);
      btnClientes.setSelected(true);
      btnProveedores.setSelected(false);
      btnUsuarios.setSelected(false);
      btnProductos.setSelected(false);
      btnAcercaDe.setSelected(false);
      btnGraficos.setSelected(false);
          btnReporteFactura.setSelected(false);
        Clientes c = new Clientes(); 
    c.setSize(953, 768);
    c.setLocation(0, 0); 
    CONTENEDOR.removeAll(); 
    CONTENEDOR.add(c, BorderLayout.CENTER); 
    CONTENEDOR.revalidate();
    CONTENEDOR.repaint(); 
    }//GEN-LAST:event_btnClientesActionPerformed

    private void btnCategoriasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCategoriasActionPerformed
     btnHome.setSelected(false);
     btnCategorias.setSelected(true);
     btnClientes.setSelected(false);
     btnProveedores.setSelected(false);
     btnUsuarios.setSelected(false);
     btnProductos.setSelected(false);
     btnAcercaDe.setSelected(false);
     btnGraficos.setSelected(false);
         btnReporteFactura.setSelected(false);
        Categoria c = new Categoria(); 
    c.setSize(953, 768); 
    c.setLocation(0, 0); 
    CONTENEDOR.removeAll();
    CONTENEDOR.add(c, BorderLayout.CENTER); 
    CONTENEDOR.revalidate(); 
    CONTENEDOR.repaint(); 
    }//GEN-LAST:event_btnCategoriasActionPerformed

    private void btnProveedoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProveedoresActionPerformed
      btnHome.setSelected(false);
      btnCategorias.setSelected(false);
      btnClientes.setSelected(false);
      btnProveedores.setSelected(true);
      btnUsuarios.setSelected(false);
      btnProductos.setSelected(false);
      btnAcercaDe.setSelected(false);
      btnGraficos.setSelected(false);
          btnReporteFactura.setSelected(false);
        Proveedor c = new Proveedor(); 
    c.setSize(953, 768); 
    c.setLocation(0, 0); 
    CONTENEDOR.removeAll();
    CONTENEDOR.add(c, BorderLayout.CENTER); 
    CONTENEDOR.revalidate(); 
    CONTENEDOR.repaint(); 
    }//GEN-LAST:event_btnProveedoresActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
    dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsuariosActionPerformed
     btnHome.setSelected(false);
       btnCategorias.setSelected(false);
       btnClientes.setSelected(false);
       btnProveedores.setSelected(false);
       btnUsuarios.setSelected(true);
        btnProductos.setSelected(false);
        btnAcercaDe.setSelected(false);
        btnGraficos.setSelected(false);
            btnReporteFactura.setSelected(false);
        usuarios c = new usuarios(); 
    c.setSize(953, 768); 
    c.setLocation(0, 0); 
    CONTENEDOR.removeAll();
    CONTENEDOR.add(c, BorderLayout.CENTER); 
    CONTENEDOR.revalidate(); 
    CONTENEDOR.repaint(); 
        
    }//GEN-LAST:event_btnUsuariosActionPerformed

    private void btnAcercaDeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAcercaDeActionPerformed
    btnHome.setSelected(false);
       btnCategorias.setSelected(false);
       btnClientes.setSelected(false);
       btnProveedores.setSelected(false);
       btnUsuarios.setSelected(false);
       btnProductos.setSelected(false);
       btnAcercaDe.setSelected(true);
       btnGraficos.setSelected(false);
           btnReporteFactura.setSelected(false);
        AcercaDe c = new AcercaDe(); 
    c.setSize(953, 768); 
    c.setLocation(0, 0); 
    CONTENEDOR.removeAll();
    CONTENEDOR.add(c, BorderLayout.CENTER); 
    CONTENEDOR.revalidate(); 
    CONTENEDOR.repaint(); 
    }//GEN-LAST:event_btnAcercaDeActionPerformed

    private void btnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProductosActionPerformed
        btnHome.setSelected(false);
       btnCategorias.setSelected(false);
       btnClientes.setSelected(false);
       btnProveedores.setSelected(false);
       btnUsuarios.setSelected(false);
       btnProductos.setSelected(true);
       btnAcercaDe.setSelected(false);
       btnGraficos.setSelected(false);
           btnReporteFactura.setSelected(false);
        Productos c = new Productos(); 
    c.setSize(953, 768); 
    c.setLocation(0, 0); 
    CONTENEDOR.removeAll();
    CONTENEDOR.add(c, BorderLayout.CENTER); 
    CONTENEDOR.revalidate(); 
    CONTENEDOR.repaint(); 
    }//GEN-LAST:event_btnProductosActionPerformed

    private void btnGraficosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraficosActionPerformed
 // Desmarcar los botones anteriores
    btnHome.setSelected(false);
    btnCategorias.setSelected(false);
    btnClientes.setSelected(false);
    btnProveedores.setSelected(false);
    btnUsuarios.setSelected(false);
    btnProductos.setSelected(false);
    btnAcercaDe.setSelected(false);
    
    // Marcar el botón de gráficos
    btnGraficos.setSelected(true);
    
    // Crear una instancia de DaoProductos para obtener la lista de productos
    DaoProductos daoProductos = new DaoProductos();
    List<productos> listaProductos = daoProductos.Listar();  // Obtener la lista de productos

    // Verificar que la lista no esté vacía antes de mostrar el gráfico
    if (listaProductos != null && !listaProductos.isEmpty()) {
        // Crear una instancia de la clase Graficos (pasando la lista de productos al constructor)
        Graficos graficoPanel = new Graficos(listaProductos);  // Ahora pasa la lista de productos al constructor

        // Configurar tamaño y ubicación del panel gráfico
        graficoPanel.setSize(953, 768);
        graficoPanel.setLocation(0, 0);

        // Limpiar el contenedor y agregar el panel de gráficos
        CONTENEDOR.removeAll();
        CONTENEDOR.add(graficoPanel, BorderLayout.CENTER);  // Asegúrate de agregar correctamente al contenedor

        // Revalidar y repintar para actualizar la interfaz de usuario
        CONTENEDOR.revalidate();
        CONTENEDOR.repaint();
    } else {
        // Mostrar mensaje si no hay productos disponibles
        JOptionPane.showMessageDialog(null, "No hay productos disponibles.");
    }
    }//GEN-LAST:event_btnGraficosActionPerformed

    private void btnReporteFacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteFacturaActionPerformed
// Desmarcar los otros botones
    btnHome.setSelected(false);
    btnCategorias.setSelected(false);
    btnClientes.setSelected(false);
    btnProveedores.setSelected(false);
    btnUsuarios.setSelected(false);
    btnProductos.setSelected(false);
    btnAcercaDe.setSelected(false);
    btnReporteFactura.setSelected(true);
    
    // Crear instancia de la ventana ReporteFactura y mostrarla
    ReporteFactura reporteFacturaFrame = new ReporteFactura();
    reporteFacturaFrame.setVisible(true);  // Muestra la ventana
    
    // Si deseas cerrar la ventana actual cuando se abre la nueva, puedes usar:
    // this.dispose(); // Esto cierra la ventana actual.
    }//GEN-LAST:event_btnReporteFacturaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }
     public void exito(String texto){
        Notification panel = new Notification(this, Notification.Type.SUCCESS, Notification.Location.TOP_RIGHT, texto);
        panel.showNotification();
    }
  public void advertencia(String texto){
        Notification panel = new Notification(this, Notification.Type.WARNING, Notification.Location.TOP_RIGHT, texto);
        panel.showNotification();
    }
    
    public void error(String texto){
        Notification panel = new Notification(this, Notification.Type.ERROR, Notification.Location.TOP_RIGHT, texto);
        panel.showNotification();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CONTENEDOR;
    private RSMaterialComponent.RSButtonMaterialIconDos btnAcercaDe;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnCategorias;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnClientes;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnGraficos;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnHome;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnProductos;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnProveedores;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnReporteFactura;
    private RSMaterialComponent.RSButtonMaterialIconDos btnSalir;
    public static RSMaterialComponent.RSButtonMaterialIconDos btnUsuarios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables

  

   
}
